flux-framework/flux-security

- .travis.yml
- config/ax_code_coverage.m4
Add the missing m4 macro for code coverage and enable travis-ci sanity check of the flux-security build so that this NEVER HAPPENS AGAIN.
> Enable simple travis build, add missing code-coverage m4

- config/ax_compiler_vendor.m4
- configure.ac
- src/Makefile.am
- src/libtomlc99/Makefile.am
- src/libtomlc99/toml_tap.c
- src/libutil/Makefile.am
- src/libutil/base64.c
- src/libutil/base64.h
- src/libutil/test/base64_test.c
This PR pulls in latest base64 and unit tests from MUNGE (current dev branch), and puts them in a new libutil directory.  Relative to flux-core, copyrights have been updated, @chu11's doc fix is in the header, and looks like @dun updated the unit tests to address some -Wall warnings.
I noticed I was compiling without -Werror, so pulled in missing ax_compiler_vendor.m4 and fixed an additional warning that popped up in libtomlc99.
Made the base64 test TAP compliant (as in flux-core) and wired into make check.
> libutil: add base64 support

- src/libtomlc99/toml.c
- src/libtomlc99/toml_tap.c
This PR adds a fix to libtomlc99 backported from upstream,
and improves our TAP test so that we no longer need to blacklist
any of the BurntSushi test input.
> libtomlc99/test: fix remaining test problems

- src/libutil/Makefile.am
Problem: gcc 7.2.0 (Ubuntu 17.10) includes -Wparentheses in -Wall.
This causes compilation of base64.c to fail.
Add -Wno-parentheses to libutil's AM_CFLAGS.
> build: fix gcc 7.2.0 warnings

- .travis.yml
- configure.ac
- src/lib/Makefile.am
- src/lib/sigcert.c
- src/lib/sigcert.h
- src/lib/test/sigcert.c
This is similar to the "zsigcert" class we used for JSON signing in the IMP prototype, except it is not dependent on czmq.  It uses TOML for the certificate format.
This is very bare bones.  Basically you can
* create a cert with new keys
* save the cert to TOML files (name and name.pub)
* load the cert from a TOML file
* compare two certs (compare their keys, that is)
* create a detached (base64) signature for an arbitrary blob
* verify a detached (base64) signature for an arbitrary blob
Major missing functionality (to be added later)
* JSON sign/verify
* CA certificate sign/verify
* support for data other than keys in the cert
I was hoping maybe we could iterate on basic stuff (like is this the right abstraction, name changing, etc) in this PR and then do the other stuff in another PR. …
> add certificate class for libsodium based sign/verify

- .travis.yml
- Makefile.am
This PR first fixes the accidentally broken travis-ci build, then adds support for GCC 5, 7, and clang 4.0 compilers. Finally, code coverage is added via coveralls just so we begin tracking coverage early (and because it was easy)
> travis-ci: add gcc 5, 7 and clang 4 builds and include code coverage

- .travis.yml
- configure.ac
- src/lib/Makefile.am
- src/lib/sigcert.c
- src/lib/sigcert.h
- src/lib/test/sigcert.c
This adds `flux_sigcert_json_loads()` and `flux_sigcert_json_dumps()` to load/dump a public version of a cert from/to a JSON string.
Eventually this could be used to include a public cert within a signed request, or to send a public cert to a CA for signing (though that requires some more discussion in #16)
This adds a jansson dependency.  Instead of requiring a newer version like flux-core and then having to build it in travis, I just allow any version and install in travis with apt.  That may be fine for this project, and I didn't want to unnecessarily complicate the travis.yml or our configure script.  We can always go there later if we need to.
> sigcert: add json_loads/dumps methods

- src/lib/sigcert.c
- src/lib/sigcert.h
- src/lib/test/sigcert.c
Add methods to get/set arbitrary data in a certificate, like the similar feature in CZMQ zcert.  This allows higher level class users to customize the certificate.
This PR also includes some cleanup, refactoring, and test improvement.
> lib/sigcert: allow user-defined metadata in the cert, and cleanup

- src/lib/sigcert.c
- src/lib/sigcert.h
- src/lib/test/sigcert.c
Add functions to allow all the TOML types to be used in metadata sections.
Some cleanup and test coverage improvement also.
> sigcert: support all TOML types in metadata accessors, cleanup

- codecov.yml
- src/lib/Makefile.am
- src/lib/sigcert.c
- src/lib/sigcert.h
- src/lib/test/keygen.c
- src/lib/test/sigcert.c
This pr adds the ability to sign a certificate with another certificate, as preparation for CA functionality.
Some practical concerns were addressed related to getting only the public portion of a cert signed:
* "cert" and "cert.pub" content no longer overlaps (as borrowed from zcert)
* `flux_sigcert_load()` now has a boolean argument to specify whether secret portion is required
* `flux_sigcert_store()` can update "cert.pub" without updating "cert"
The signature is calculated over json-serialized metadata and public key, skipping an existing signature if present.
There is also some internal cleanup to allow keys and signatures to be manipulated and base64-encoded without needing to malloc.
Unit tests updated.
As a bonus and for inspiration, I added a toy keygen program to play with:
``` …
```
> sigcert: add certificate signing capability, cleanup

- src/lib/sigcert.c
- src/libutil/Makefile.am
- src/libutil/cf.c
- src/libutil/cf.h
- src/libutil/test/cf.c
- src/libutil/test/tomltk.c
- src/libutil/tomltk.c
- src/libutil/tomltk.h
This is a first cut at a config class.  It has no tests - I'm posting it for early review of API and concepts.  Here's the header for convenient reference:
```c// flags for cf_table_update
enum {
CF_STRICT = 1,     // parse error on unknown keys
CF_ANYTAB = 2,     // allow unknown keys if they are tables
};
// allowed types
// CF_ARRAY | <type> means array of <type> elements, where <type>
// is any type except CF_UNKNOWN, CF_TABLE, or CF_ARRAY.
enum cf_type {
CF_UNKNOWN      = 0,
CF_TABLE        = 1,
CF_INT64        = 2,
CF_DOUBLE       = 3,
CF_BOOL         = 4,
CF_TIMESTAMP    = 5,
CF_STRING       = 6,
CF_ARRAY        = 0x10,
};
struct cf_table;
struct cf_option {
const char *key;
enum cf_type type;
bool required;
};
#define CF_OPTIONS_TABLE_END { NULL, 0, false }
/* Create an empty …
```
> libuitl/cf: add config class

- src/libutil/Makefile.am
- src/libutil/kv.c
- src/libutil/kv.h
- src/libutil/test/kv.c
This PR adds a new `struct kv` class that implements a simple "key=value\0" serialization that should be easier to audit than JSON encoding.
In addition, the following changes were made to the `sigcert` class:
* move from `lib` to `libutil`, drop `flux_` namespace prefix
* internally represent "metadata" (arbitrary user data) using `struct kv`
* drop json certificate serialization, add base64 certificate serialization
> add simple key=val encoding capability

- src/libutil/kv.c
- src/libutil/kv.h
- src/libutil/test/kv.c
This PR changes serialization from "key=val\0key=val\0..." to "key\0val\0key\0val\0...".
This allows `kv_entry_key()` to return a key without needing to copy it to a user-provided buffer.
> libutil/kv: eliminate kv_keybuf_t by changing serialization

- src/libutil/kv.c
- src/libutil/kv.h
- src/libutil/test/kv.c
Prepend a "type designator" byte to kv values so that string, int64_t, double, bool, and timestamp typed values can be supported.   Add typed get, put, and iteration value access functions.
Add `kv_join()` to add entries from one kv object to another, optionally prepending a key prefix; and add `kv_split()` to do the reverse.
These two relatively simple additions allow typed, hierarchical data such as TOML or JSON to be serialized as a flat kv buffer, and extracted again.
> libutil/kv: add typed values and split/join capability

- src/libutil/cf.c
- src/libutil/cf.h
- src/libutil/test/cf.c
This PR adds a `cf_update_glob()` call to iteratively call `cf_update_file()` on all files matching a pattern. It is meant to be used for loading TOML files from a `conf.d` style directory, e.g. `cf_update_glob (cf, "/etc/conf.d/*.toml")`.
Some decisions here were made that probably need to be vetted. The call only updates the `cf` table if *all* files matching the pattern parse and are loaded successfully. That seemed the most sane way to do it.
The return value from the function is the number of files successfully parsed, or -1 on an unrecoverable error (ENOMEM or if `glob(3)` can't open a directory). A return value of zero therefore means there was no error, but no files matched the pattern. I figured this was not necessarily an error condition, but the caller may want to test for it.
> libutil/cf: add interface to update a cf table with multiple files

- src/libutil/kv.c
- src/libutil/kv.h
- src/libutil/test/kv.c
@grondo - what do you think about this change to the kv api which replaces the typed kv_get_TYPE, kv_put_TYPE functions with single varargs functions?
This seemed like a good idea until I recalled the fact that one can get into trouble with the lack of type promotion through varargs interfaces, specifically
```c
kv_put (kv, key, KV_INT64, 42);
```
causes an out of bounds memory access. You need
```c
kv_put (kv, key, KV_INT64, 42LL);
```
Maybe not such a good idea in a security sensitive situation?
OTOH, the reduction in API footprint is nice, especially given that this class may end up partially wrapped in several places.
Hope you don't mind me posting this half baked idea just to get your feedback.
> libutil/kv: add varargs get/put

- src/libutil/Makefile.am
- src/libutil/kv.c
- src/libutil/kv.h
- src/libutil/sigcert.c
- src/libutil/sigcert.h
- src/libutil/test/keygen.c
- src/libutil/test/kv.c
- src/libutil/test/sigcert.c
- src/libutil/timestamp.c
- src/libutil/timestamp.h
- src/libutil/tomltk.c
This PR makes a few minor changes to the kv class
* restore header comment that was somehow dropped before merge of pr #32 
* factor out time_t/string conversion functions to timestamp.[ch]
* rename kv_raw_encode() to kv_encode(), kv_raw_decode() to kv_decode()
Then it reworks the sigcert class to use kv internally instead of JSON, and to replace JSON serialization with kv serialization.
> libutil/sigcert: use kv serialization not JSON

- src/libutil/cf.c
- src/libutil/cf.h
- src/libutil/test/cf.c
- src/libutil/tomltk.c
- src/libutil/tomltk.h
A number of `cf_t *` parameters in the cf class should have been tagged `const` for better clarity.
> libutil/cf:  make some cf_t parameters const

- .travis.yml
- Makefile.am
- configure.ac
- src/imp/Makefile.am
- src/imp/imp.c
- src/imp/imp.conf.d/imp.toml
- src/imp/imp_state.h
- src/imp/impcmd-list.c
- src/imp/impcmd.c
- src/imp/impcmd.h
- src/imp/privsep.c
- src/imp/privsep.h
- src/imp/sudosim.c
- src/imp/sudosim.h
- src/imp/test/impcmd.c
- src/imp/test/privsep.c
- src/imp/version.c
- src/imp/whoami.c
- src/libutil/kv.h
- t/Makefile.am
- t/sharness.d/10-sudo.sh
- t/sharness.sh
- t/t0000-sharness.t
- t/t0100-sudo-unit-tests.t
- t/t1000-imp-basic.t
This PR adds basic functional skeleton for the IMP including:
* Support for directory of TOML config files under a directory like `imp.conf.d/*.toml`. For now config is only loaded from build directory, but support is there to load from hard-coded system configuration directory by building a separate binary (e.g. flux-imp.installed or something).
* Implementation of privilege separation when IMP is running setuid. The IMP process will fork off a child that drops privileges to the real UID. The "privliged parent" and "unprivileged child" are connected with a pair of pipes. The child is meant to process all input from the untrusted source, and push data back to the parent over the pipe in a more restricted format. Nothing uses this yet.
* Support for running under sudo by simulating a …
> Add basic skeleton for the IMP

- src/imp/Makefile.am
- src/imp/imp.c
- src/imp/imp_log.h
- src/imp/privsep.c
- src/imp/test/imp_log.c
- src/imp/testconfig.c
- t/t1000-imp-basic.t
Posting an early version of this (no tests yet) in case @garlick wants to base casign tests off the result (and give early feedback). Will try to work on a few tests tonight, though I just remembered there is a school function, so perhaps not until tomorrow AM.
Sorry this functionality wasn't here from the start.
> imp: Allow config file pattern to be overridden for build-tree IMP

- codecov.yml
- src/imp/Makefile.am
- src/imp/casign.c
- src/imp/impcmd-list.c
- src/libutil/sigcert.c
- src/libutil/sigcert.h
- src/libutil/test/sigcert.c
- t/Makefile.am
- t/src/ca.c
- t/src/certutil.c
- t/src/cf.c
- t/src/keygen.c
- t/t1001-imp-casign.t
I thought I'd put this up for comment (mainly to see if I'm using privilege separation correctly).
This adds a `casign` subcommand that accepts an unsigned user cert on stdin, signs it with the CA cert, and emits the signed user cert on stdout.  It's a very tentative stab at implementing #42.
It would be called by a flux-core keygen utility as part of generating a user cert.
The unpriv child just reads the cert in encoded kv form on stdin and adds it to the kv that is sent to the priv parent.  The parent uses its privilege to access the CA cert and uses it to sign the user cert (as the real uid), then emits the signed cert in encoded kv form on stdout.
No TOML config file, no source tree cert location, and no tests yet.
> imp/casign: add casign subcommand

- src/libtomlc99/test/toml.c
- src/libutil/ca.h
- src/libutil/sigcert.c
This PR includes a few commits pulled out of #53 that were not related.
Fix a typo in the new TOML UTF8 tests (will need to be applied to flux-core too), and tweak some comments.
> cleanup comments and test

- src/imp/casign.c
- src/libutil/ca.c
- src/libutil/ca.h
- src/libutil/sigcert.c
- src/libutil/test/ca.c
- src/libutil/test/sigcert.c
- src/libutil/test/signer.c
- t/src/ca.c
- t/t1001-imp-casign.t
This PR expands the metadata included in each Flux certificate.
The CA cert is now self-signed through the same process that user certs are signed, so it now includes the same metadata:
* **uuid** -- a unique id for the cert
* **userid** -- real userid of the user that signed the cert
* **ctime** -- certificate create time
* **xtime** -- certificate expiration time
* **domain** -- (new) domain name string from the CA configuration, e.g. `HYPE.LLNL.GOV`
* **issuer** -- (new) the uuid of the cert that signed this cert
* **max-sign-ttl** -- max TTL for signatures by this cert (ignored in the CA cert for now)
* **algorithm** -- (new) always `ed25519` right now
The uuid/issuer relationship prepares for CA key management (#52), where the `issuer` in a user cert can be used to find one of …
> improve certificate metadata

- src/lib/context.c
- src/lib/context_private.h
- src/lib/sign.c
- src/lib/test/context.c
- src/libutil/test/cf.c
- t/t1002-sign-munge.t
This is a list of small fixes split off of ongoing work. I wanted to submit these before they got too out of date.
The main functionality changes are minor and to only the private security context interface in `context_private.h`. The allow an existing `cf_t` config to be set directly in `flux_security_t` with a new `security_set_config()` call, and add a way to return the entire `cf_t` stored in the `flux_security_t` context by passing a `NULL` as the key in `security_get_context`.
These are needed to allow the IMP, which parses its own config, to share all the config tables it has with the security handle.
The minor fixes were found along the way and include fix for off-by-one error and leak found in sign.c, and a small typo in cf_copy() test.
> enhance private context interface and other small fixes

- config/ac_pkgconfig.m4
- configure.ac
- src/lib/Makefile.am
- src/lib/flux-security.pc.in
This PR adds a .pc file for libflux-security.so and makes sure it gets installed into the proper directory.
> build: clean up library install

- .travis.yml
- NEWS.md
For consistency with other flux-framework projects, add a v0.1.0 entry to the NEWS.md file.
Copy the travis-ci deploy stanza from other flux-framework projects to allow auto-release upload to GitHub on the next flux-security tag. (There isn't a good way to test this now, so fixes might be required on the next tag)
> Update NEWS.md with v0.1.0 entry, add auto-release to travis-ci deploy section

- Makefile.am
- configure.ac
- etc/Makefile.am
- etc/sign.toml
- src/lib/Makefile.am
This PR moves the default config file location to `$sysconfdir/flux/security/conf.d`, and installs a default config file for signing.
The config file location change keeps flux-core and flux-security configs separate so that security components like the IMP don't parse irrelevant (and possibly voluminous or conflicting) TOML, and vice versa.
The default config file allows the installed flux-security package to be functional without manual configuration.  At the moment this allows code in flux-core to configure flux-security with a NULL config pattern and get something that works, which is convenient while we evaluate how to share configuration and security contexts within a flux instance.  When flux-security is packaged as an RPM or deb, we would tag this config file as a "noreplace" so …
> etc: install config file for signing

- NEWS.md
As discussed, prepare for a flux-security v0.2.0 tag with a new NEWS entry.
> Add NEWS item for flux-security v0.2.0

- .gitignore
- config/ax_split_version.m4
- configure.ac
- src/lib/Makefile.am
- src/lib/test/version.c
- src/lib/version.c
- src/lib/version.h.in
This adds functions and macros for accessing the flux-security version, as was done for flux-core in flux-framework/flux-core#1817
> add flux-security version accessors

- COPYING.LESSER
- src/lib/context.c
- src/lib/context.h
- src/lib/sign.c
- src/lib/sign.h
- src/lib/sign_curve.c
- src/lib/sign_munge.c
- src/lib/sign_none.c
- src/libca/ca.c
- src/libca/sigcert.c
- src/libutil/cf.c
- src/libutil/kv.c
- src/libutil/timestamp.c
- src/libutil/tomltk.c
This adds an LGPLv2.1+ boiler plate to all installed headers, and to all code linked in to libflux-security.la.
Fixes #83
> license: change boiler plate for library code to LGPLv2.1+

- src/lib/context.c
- src/lib/test/context.c
- src/libutil/Makefile.am
- src/libutil/aux.c
- src/libutil/aux.h
- src/libutil/test/aux.c
Following on flux-framework/flux-core#1797, switch the implementation behind `flux_security_aux_set()` and `flux_security_aux_get()` over to the common one from flux-core (and pull that in with its unit test).
> lib: make flux_security_aux_get/set behave like flux-core API

- src/imp/Makefile.am
- src/lib/Makefile.am
- src/libca/Makefile.am
- src/libutil/Makefile.am
- t/Makefile.am
This PR tracks the build system changes for `version.h` in flux-framework/flux-core#1824.
Since `version.h` is generated by configure, it should not be included in `make dist`.
For VPATH builds, `-I$(top_builddir)` then needs to be searched for includes, not just `-I$(top_srcdir)`.
> build: don't distribute version.h

- configure.ac
- src/lib/Makefile.am
Copy @chu11's scheme for maintaining library version information in top-level `configure.ac`. Start the `libflux-security.so` library version info at `1:0:0`.
> add version support for libflux-security.so

- NEWS.md
Add a `NEWS.md` entry for v0.3.0 in preparation for a tag. (This is currently based on top of #93, will rebase when/if that is merged.)
> Add NEWS entry for flux-security v0.3.0

- .travis.yml
- Makefile.am
- configure.ac
- src/imp/test/privsep.c
- src/lib/sign_curve.c
- src/lib/test/context.c
- src/libca/test/ca.c
- src/libca/test/sigcert.c
- src/libtomlc99/test/toml.c
- src/libutil/test/cf.c
- src/libutil/test/tomltk.c
- t/Makefile.am
- t/sharness.d/01-asan.sh
- t/sharness.d/10-sudo.sh
- t/src/sanitizers-enabled.c
- t/src/verify.c
- t/t0000-sharness.t
- t/t0100-sudo-unit-tests.t
- t/t1000-imp-basic.t
- t/t1001-imp-casign.t
- t/t1003-sign-curve.t
This PR adds an `--enable-sanitizers` option to `configure` which turns on `-fsanitize=address` and `-fsanitize=undefinied` (along with other requisite options), and enables a build with this option in travis-ci.
Along the way some minor fixes (mostly in tests) were discovered and fixed.
At the top-level Makefile, some default ASAN_OPTIONS and UBSAN_OPTIONS are set, so that `make check` from top builddir will run successfully. (However, it won't work from a subdir, so perhaps another method is required)
Some shenanigans were required to work around "issues" with LSan and sudo/setuid.
I can add more detail later, but wanted to get this up to see how Travis goes.
> Add option to build with asan and ubsan, and fix discovered errors

- .github/workflows/main.yml
- .mergify.yml
- t/t1000-imp-basic.t
- t/t1002-sign-munge.t
This PR fixes a couple tests in flux-security that are broken on LC clusters.
Nothing too major:
* Update the method for determining system munged socket (newer MUNGE versions have another line that contains "socket" in the `--help` output)
* Skip setuid tests in the IMP testsuite when running on a filesystem with nosuid (or other scenarios where setuid permissions cannot be set on executables)
> testsuite: fix tests that do not work in some environments

- configure.ac
- src/imp/Makefile.am
- src/imp/exec/exec.c
- src/imp/exec/user.c
- src/imp/exec/user.h
- src/imp/imp.c
- src/imp/imp_log.h
- src/imp/impcmd-list.c
- src/imp/passwd.c
- src/imp/passwd.h
- src/imp/privsep.c
- src/imp/privsep.h
- src/imp/test/passwd.c
- src/imp/test/privsep.c
- src/imp/testconfig.c
- src/libutil/cf.c
- src/libutil/cf.h
- src/libutil/test/cf.c
- t/Makefile.am
- t/t2000-imp-exec.t
This PR adds a minimal working version of the `flux-imp exec` subcommand.
This version takes input as JSON on stdin. The current format requires a single key "J", expected to contain the users signed jobspec.
`flux-imp exec` reads the path to the job shell to execute plus 1 argument from the cmdline. This allows simply inserting `flux-imp exec` in front of the job shell invocation already being done by the job-exec module.
With the exec command comes a new `[exec]` table in the IMP's configuration. In order for `flux-imp exec` to be functional, the table must contain at least the following keys
```toml
[exec]
allowed-users = [ "list of users allowed to run imp exec" ]
allowed-shells = [ "list of shell paths allowed for imp exec" ]
```
Without either of these config keys either the IMP …
> imp: add limited exec support

- src/imp/exec/exec.c
- t/t2000-imp-exec.t
It is giving me some heebie-jeebies that a system instance install of flux-core with the current flux-security where the IMP is *not* installed setuid will allow any user to run anything as user `flux`.
This PR cleans that up by having the IMP refuse to exec anything by default when installed unprivileged. Since the unprivileged exec is used in testing, a new config parameter `exec.allow-unprivileged-exec` is added.
> imp: do not allow unprivileged exec by default 

- src/imp/Makefile.am
- src/imp/impcmd-list.c
- src/imp/kill.c
This PR adds a `kill` command to the IMP, used as `flux-imp kill SIGNAL PID`. If the user running the IMP is in the `exec.allowed-users` config, and the IMP is installed setuid, then this command allows the requesting user to kill processes running as other users as long as the process is running in a cgroup owned by the requesting user.
The current version assumes that the multiuser Flux has been started by systemd with `Delegate=yes`.
I'm not exactly sure how to do any type of testing for this new code. I think within travis-ci builders, we might find that the cgroup filesystem isn't even mounted.
I will at least try to push some sanity checks for the failure modes of the `kill` subcommand -- user not in allowed-users, etc.
> imp: add a kill command

- src/imp/kill.c
- t/Makefile.am
- t/t2001-imp-kill.t
This PR adds the `flux-imp kill` tests promised in #110. 
Additionally a memleak fix found along the way, and for testing, allow non-root users running the IMP to kill their own processes. (Still pondering if this one should require an option.)
> imp: add tests for flux-imp kill, fix discovered issues

- NEWS.md
Update NEWS.md for flux-security v0.4.
With the basic flux-imp `exec` and `kill` "working" for some definition thereof, now might be a good time to tag a flux-security release, so we can update the version built in flux-core test docker images.
> Add release notes for flux-security v0.4

- configure.ac
For consistency to flux-core issue #3239, increase the minimum
jansson version to 2.10.
> build: bump minimum jansson version to 2.10

- .mergify.yml
flux-security has been migrated from travis-ci.org to travis-ci.com.
I think this is the one required change due to the migration.
> update mergify config for move to travis-ci.com

- src/imp/Makefile.am
- src/imp/exec/exec.c
- src/imp/imp.c
- src/imp/testconfig.c
- src/lib/context.c
- src/lib/context.h
- src/lib/test/context.c
- src/libutil/Makefile.am
- src/libutil/cf.c
- src/libutil/cf.h
- src/libutil/kv.c
- src/libutil/strlcpy.c
- src/libutil/strlcpy.h
- src/libutil/test/cf.c
- t/Makefile.am
- t/t0101-cf-path-security.t
As described in #101, TOML config files opened by the IMP should be checked for secure permissions and ownership. This PR adds a "paranoid" mode to `libutil/cf.c` which is enabled by default whenever the effective UID of the process is `0` or does not match the real UID (setuid mode). This mode can also be enabled by explicitly setting `enable-path-paranoia = true` in a `cf_t` object before calling one of the functions that reads from files (e.g. `cf_update_glob()`, `cf_update_file()`).
Paranoid mode can also be explicitly _disabled_ by setting `disable-path-paranoia = true`. This is only used (and only designed) for testing, where it is convenient to test the IMP running in sharness tests when reading from config files in the sharness trash directory with regular user ownership. …
> check file permissions and ownership of configuration when running privileged code

- configure.ac
- src/imp/Makefile.am
- src/imp/impcmd-list.c
- src/imp/privsep.h
- src/imp/run.c
- src/libutil/Makefile.am
- src/libutil/cf.c
- src/libutil/cf.h
- src/libutil/kv.c
- src/libutil/kv.h
- src/libutil/path.c
- src/libutil/path.h
- src/libutil/test/cf.c
- src/libutil/test/kv.c
- src/libutil/test/path.c
- t/Makefile.am
- t/t2002-imp-run.t
As described in #120, the IMP will need to assist the Flux system instance with execution of job prolog and epilog scripts, which typically require elevated privileges.
Instead of adding separate `flux-imp prolog` and `flux-imp epilog` subcommands, this PR adds a new `run` subcommand to the IMP which is invoked like `flux-imp run COMMAND`. Commands to execute under the IMP `run` subcommand are added to the IMP configuration under a `run` table by name, e.g. `[run.prolog]` and `[run.epilog]`. Required keys in these run command tables include:
* `path` - the path to the executable to run
*  `allowed-users` - an array of usernames that are allowed to run this command, e.g. `[ "flux" ]`
*  `allowed-environment` - an array of environment variables and/or `glob(7)` patterns which match …
> imp: add run subcommand

- .mergify.yml
Problem: Mergify.io has deprecated the strict merge mode action:
https://blog.mergify.io/strict-mode-deprecation/
Replace the strict mode configuration with a default queue with a
rebase action which should be equivalent.
> mergify:  replace strict merge with queue+rebase

- src/imp/exec/exec.c
- src/libutil/kv.c
- src/libutil/kv.h
- src/libutil/test/kv.c
- t/t2000-imp-exec.t
This PR addresses #127.
Instead of supporting only 1 argument, all arguments passed in the call the `flux-imp exec` are passed along to the job shell. This will allow the system instance to add extra options to the job shell based on configuration, e.g. a `--reconnect` option.
> imp: support multiple arguments to job shell in exec

- .github/workflows/main.yml
The auto-deploy actions for the last flux-security tag didn't work.
I think I've run down the problem (of course, you can't check without another tag), with fixes in this simple PR. Since the workflow is modified, this may require a manual merge. Hopefully things just work next time.
> fix auto-deploy of flux-security release on tag

- doc/Makefile.am
- doc/man3/flux_security_aux_set.rst
- doc/man3/flux_security_create.rst
- doc/man3/flux_security_last_error.rst
- doc/man3/flux_sign_unwrap.rst
- doc/man3/flux_sign_wrap.rst
- doc/man3/index.rst
- doc/manpages.py
This adds a man page for `flux_security_aux_set()` and `flux_security_aux_get()`, and fills in some gaps in the recently added signing man pages.
> doc: add flux_security_aux_set(3)

- doc/man5/flux-config-security-imp.rst
Problem: The flux-config-security manpage was typoed as
flux-security-config.
Fix the typo.
> doc: fix manpage typo

- configure.ac
- src/imp/kill.c
- t/t2001-imp-kill.t
- t/t2002-imp-run.t
This PR allows the IMP `kill` functionality to work on distros and configurations where unified cgroups are in use.
A simple function is added which determines whether unified cgroups are active, and the mount point for the cgroups hierarchy, using the rules described at https://systemd.io/CGROUP_DELEGATION/. Otherwise, changes are minimal. 
I've tested this out on a local Ubuntu 22.04 system, but it would be good if @garlick could test this on his raspbian system as well.
> imp: fix kill functionality with unified cgroups hierarchy

- .github/workflows/main.yml
Problem: A typo in the 'prep release' step of the Github Workflow
causes the auto deploy of tags to releases to fail.
Fix the typo so the next auto deploy works.
> github: fix typo in deploy action

- config/x_ac_pam.m4
- configure.ac
- doc/man5/flux-config-security-imp.rst
- doc/test/spell.en.pws
- src/imp/Makefile.am
- src/imp/exec/exec.c
- src/imp/exec/pam.c
- src/imp/exec/pam.h
- src/imp/version.c
- src/test/docker/checks/Dockerfile
- t/Makefile.am
- t/t2003-imp-exec-pam.t
This is being put up as WIP for comments and review. It should not be merged until after #150.
This provides a solution to flux-framework/flux-pmix#40 and #148 where users have hit issues running on system-instance clusters where max locked memory must be increased. A few things to note here:
- The system instance will now require a PAM configuration file in `/etc/pam.d/flux` and (presumably) a `limits.conf` file with hard and soft resource limits. This should be added to the Flux Administrator's Guide.
- When running in a container, the `pam_limits.so` dependency will fail if a `limits.conf` file does not exist, a `/etc/pam.d/flux` file does not exist, or if the configured limits exceed the limits allocated to the container. This may require changes to the fluxorama containers to …
> imp: exec: add PAM session support

- NEWS.md
This adds release notes for a v0.8.0. We had talked about pushing this out with the next TOSS release but I forgot to update `NEWS.md`.
> NEWS.md: add release notes for v0.8.0

- src/imp/pidinfo.c
Problem: The access(2) check in pid_kill_children() seems to fail with ENOENT when /proc is mounted with hidepid=2, even though the flux-imp process is running with effective UID 0. This causes the IMP to abort the kill operation with:
failed to signal flux-imp children: No such file or directory
Remove the brittle access(2) check and let the subsequent fopen(3) fail if the process no longer exists. This will trigger the fallback code, which will presumably find no processes to signal if the target PID really no longer exists, but this is preferrable to outright failure.
Fixes #154
> imp: fix kill operation when /proc is mounted with hidepid=2

- .github/workflows/main.yml
Problem: Github has deprecated set-output and nodejs 12 actions.
Update checkout and codecov actions. Also update the auto-release action to use softprops/action-gh-release@v1 since the github release and upload actions are no longer maintained.
> github: update actions workflow

- debian/rules
Problem: An example sign.toml is packaged in the resulting package after 'make deb', but this may overwrite an existing admin-installed config.
Remove all config files from the test package created by 'make deb'.
> deb: do not package config file

- .github/workflows/main.yml
- .typos.toml
- doc/test/spell.en.pws
- src/imp/exec/user.c
- src/imp/kill.c
- src/imp/privsep.h
- src/lib/sign.c
- src/lib/sign_curve.c
- src/libutil/cf.c
- src/libutil/test/cf.c
- src/libutil/test/kv.c
- src/test/checks_run.sh
- src/test/docker/checks/Dockerfile
- t/src/cf.c
As with some other flux-framework projects, run the `crate-ci/typos` action in CI to detect typos.
Add a `.typos.toml` config file to exclude some files that are maintained elsewhere.
Fix detected typos.
> detect typos during CI

- Makefile.am
- src/libtomlc99/Makefile.am
The flux-security LICENSE file is not included in the `make dist` tarball.
Add it and the libtomlc99 LICENSE and README as well.
> ensure LICENSE is included in distribution tarball

- README.md
- debian/control
- debian/rules
- doc/requirements.txt
- src/imp/exec/exec.c
- t/t2000-imp-exec.t
The debian package created by `make deb` was accidentally missing `--enable-pam` so had no PAM support.
Furthermore, the IMP silently ignores the `pam-support = true` option in the config when built without PAM.
Add PAM development packages to the suggested requirements for this project and in the `debian/control` file, and add `--enable-pam` to the debian package build by default. Add an error if `pam-support=true` is specified but the IMP was not built with PAM enabled, and add a test for this error.
> build: enable PAM in `make deb`

- NEWS.md
Problem: There are no release notes in NEWS.md for v0.9.0.
Add a set of notes for the new features and fixes since v0.8.0 to NEWS.md.
> NEWS.md: add release notes for v0.9.0

- .mergify.yml
- src/imp/imp.c
- src/imp/run.c
- src/test/generate-matrix.py
The CI in flux-core is being modernized to drop el7, bionic, and fedora35 images, and add Debian bookworm and fedora38.
Make similar changes here so that we can ensure flux-security is tested on the same sets of software as in flux-core's CI.
Include some minor fixes caught by more modern compilers now used in CI.
> ci: update build matrix to more closely match flux-core

- src/test/generate-matrix.py
This PR simply adds `--enable-pam` to many of the ci builders. We can still consider auto-enabling PAM in the build, but for now this is a simpler approach.
> ci: add `--enable-pam` to most CI builds

- configure.ac
- src/libutil/kv.c
- src/libutil/test/kv.c
Problem: rfc38 specifies test vectors for kv, but these are not used by unit tests.
Add a new unit test section that covers these vectors.
Also, grow an internal static buffer in case very large doubles are ever encoded.
> testsuite: cover rfc38 kv test vectors

- NEWS.md
We should probably create a new flux-security release to incorporate the fix for #171.
This just adds release notes for a flux-security v0.10.0 release. Note sure if we have more planned work for the next tag at this time.
> add release notes for v0.10.0

- config/ac_pkgconfig.m4
- config/am_check_pymod.m4
- configure.ac
- src/libtomlc99/Makefile.am
Here are some fixes autoreconf warnings noted in  #178.  Much of this is just pulling over what others have already done in flux-core.
Fixes #178
> build: address warnings from autogen.sh

- t/t2001-imp-kill.t
This fixes a few problems in the last test of `t2001-imp-kill.t` which was being skipped more often than not and thus flew under the radar.
> testsuite: fix imp kill test

- .readthedocs.yaml
- src/imp/exec/exec.c
- src/imp/pidinfo.c
- src/imp/test/pidinfo.c
- src/lib/sign.h
- src/libutil/test/cf.c
- src/libutil/test/tomltk.c
- src/libutil/timestamp.c
- src/test/generate-matrix.py
- t/src/getpwuid.c
- t/src/sign.c
This PR fixes some musl libc portability issues in flux-security and adds an alpine Linux CI build so we don't break it again.
> port to musl and add alpine CI build

- NEWS.md
A tagged version of flux-security that builds on alpine will be required for a flux-core alpine build for CI, since the first thing that is done is to build flux-security in the image. Therefore, let's create a v0.11. 0 tag for his purpose. Not much changed besides the porting effort, but tags are cheap...
> NEWS.md: add release notes for v0.11.0

- doc/requirements.txt
- src/imp/Makefile.am
- src/imp/cgroup.c
- src/imp/cgroup.h
- src/imp/exec/exec.c
- src/imp/imp.c
- src/imp/imp_state.h
- src/imp/signals.c
- src/imp/signals.h
- src/test/docker/docker-run-checks.sh
- t/t2000-imp-exec.t
This PR updates the IMP to translate SIGUSR1 to SIGKILL for `flux-imp exec` as defined in RFC 15.
Additionally, if possible, the IMP will signal all members of its cgroup (besides itself) when delivering SIGKILL.
Finally, to better handle returning the proper wait status to _its_ parent, when the child of the IMP is terminated by a signal, the IMP raises that same signal to itself.
This is WIP pending real system testing.
> imp: exec: send SIGKILL to cgroup/children on SIGUSR1

- src/imp/cgroup.c
- src/imp/cgroup.h
- src/imp/exec/exec.c
- src/imp/signals.c
- t/t2000-imp-exec.t
This PR modifies `imp exec` to wait for an "empty" cgroup before exiting, where empty means `cgroup.procs` contains only the IMP's own PID.
> imp: exec: wait for job cgroup to be empty before exiting

- src/imp/run.c
- t/t2002-imp-run.t
This PR changes the `flux-imp run` implementation to have the privileged IMP linger and delegate signals to its child, which the calling user would not otherwise have privilege to do.
WIP while I test this out locally.
> allow privileged IMP to linger during `flux-imp run` to support signal forwarding

- NEWS.md
Problem: NEWS.md doesn't mention the latest PR that was merged before tagging 0.12.0.
Add it.
> NEWS.md: add last-minute autogen fix

- config/am_check_pymod.m4
- configure.ac
Problem: distutils StrictVersion is deprecated (along with distutils itself), but it is still used in testing for sphinx and docutils in configure.ac.
Drop distutils and use packaging.version.Version instead.
> configure: do not use distutils StrictVersion

- src/imp/run.c
- src/imp/signals.c
- src/imp/signals.h
- t/t2002-imp-run.t
This PR fixes #194 by allowing the IMP to forward signals to the entire process group with `flux-imp run`.
Additionally, an issue with blocked signals (specifically in `t2002-imp-run.t`) was fixed here  and a test for SIGINT handling added to the testsuite.
> forward signals to entire process group in `flux-imp run`

- NEWS.md
Problem: There are no release notes for flux-security v0.13.0.
Add them.
> NEWS.md: add release notes for flux-security v0.13.0

- src/imp/cgroup.c
- src/imp/pidinfo.c
Problem: the cgroup name prefix of "imp-shell" is hard coded in the IMP to select a signal forwarding strategy that ought to apply to flux-housekeeping/epilog/prolog if we move them from the system to the user systemd instance.
Check for the "flux-" unit name prefix too.
> imp: use cgroup_kill when cgroup begins with flux-

- src/imp/run.c
This prepares to let `imp run` run as the main process in a user systemd instance
- wait for cgroup to empty out before exiting
- call sd_notify() so Type=notify unit can be used (and allow NOTIFY_SOCKET to be passed thru the environment).
It is built on top of #201
> imp run: wait for cgroup and call sd_notify()
